In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)
tf.enable_eager_execution()

1.13.1


In [2]:
# one-hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]


x_data = np.array([[h]], dtype=np.float32)
# One cell RNN input_dim(4) -> output_dim(2)
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = layers.RNN(cell, return_sequences=True, return_state=True) # analogous to tf.nn.dynamic_rnn
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.5986685  -0.67496705]]], shape: (1, 1, 2)
states: [[ 0.5986685  -0.67496705]], shape: (1, 2)


In [3]:
# equivalent to above case
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,
                      return_state=True)

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.25826487 0.7410325 ]]], shape: (1, 1, 2)
states: [[0.25826487 0.7410325 ]], shape: (1, 2)


In [4]:
# One cell RNN input_dim (4) -> output_dim(2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {} \n'.format(states, states.shape))


x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[-0.38393524 -0.49212947]
  [ 0.3678692  -0.58783686]
  [ 0.28818828 -0.9119462 ]
  [ 0.02293238 -0.9390607 ]
  [-0.4459385  -0.62187123]]], shape: (1, 5, 2) 

states: [[-0.4459385  -0.62187123]], shape: (1, 2) 



In [5]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch: 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {} \n'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[ 0.30115566  0.2021718 ]
  [-0.6787076  -0.28210723]
  [ 0.13306417 -0.00577014]
  [-0.45528594  0.5234867 ]
  [ 0.10249203 -0.7427387 ]]

 [[-0.46744066 -0.4308175 ]
  [ 0.74027026 -0.4770149 ]
  [-0.3456312   0.87131697]
  [-0.7782346  -0.24811593]
  [ 0.14946221 -0.10916533]]

 [[-0.40861747  0.43085325]
  [-0.5528177  -0.10179915]
  [-0.15600687 -0.71685785]
  [ 0.19676071 -0.2561349 ]
  [-0.2915195   0.6380909 ]]], shape: (3, 5, 2) 

states: [[ 0.10249203 -0.7427387 ]
 [ 0.14946221 -0.10916533]
 [-0.2915195   0.6380909 ]], shape: (3, 2) 

