In [2]:
import numpy as np

# ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# ar = np.array([0, 2, 4, 6, 8, 10, 12, 14, 14, 14])
ar = np.array([[0, 2], [4, 6], [8, 10], [12, 14], [14, 14]])
# ar = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
ar

dimension = 15
ar2d = np.zeros((len(ar), dimension))
print(ar2d)
print('----------')
for i,sequence in enumerate(ar):
    ar2d[i, sequence] = 1.

print(ar2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
----------
[[1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
